### ISSUE TITLE
November 2022 Polyglots Newsletter

### ISSUE THREAD

**Issue by varlese** [varlese/polyglots#1]
## Publish date: 
November 22, 2022 

## Tasks:
- [ ] Copy and draft [email template](https://docs.google.com/document/d/1TRxe7fWSv1XJ7qlP5JDQnNC8W6HQbuShxPVlSlhF7W0/edit?usp=share_link)
- [ ] Copy and draft [P2 template](https://docs.google.com/document/d/1P8Z_it88ZAkySVMprOCnmIzGg2dn60IrRnjhqqpUATQ/edit?usp=share_link)
- [ ] Share in Polyglots Slack channel for input
- [ ] Create issue in Marketing for review ([example](https://github.com/WordPress/Marketing-Team/issues/129))
- [ ] Update [Mailchimp stats](https://docs.google.com/spreadsheets/d/1N3xLnISDAgduCtgzuHd0Gz3nu7cjQIBZ2Q2f8rFD7sk/edit?usp=share_link)
- [ ] Import email to Mailchimp
